export const EDOMEX_MUNICIPALITIES = [
  'Acambay de Ruiz Castaneda',
  'Acolman',
  'Aculco',
  'Almoloya de Alquisiras',
  'Almoloya de Juarez',
  'Almoloya del Rio',
  'Amanalco',
  'Amatepec',
  'Amecameca',
  'Apaxco',
  'Atenco',
  'Atizapan',
  'Atizapan de Zaragoza',
  'Atlacomulco',
  'Atlautla',
  'Axapusco',
  'Ayapango',
  'Calimaya',
  'Capulhuac',
  'Coacalco de Berriozabal',
  'Coatepec Harinas',
  'Cocotitlan',
  'Coyotepec',
  'Cuautitlan',
  'Cuautitlan Izcalli',
  'Chalco',
  'Chapa de Mota',
  'Chapultepec',
  'Chiautla',
  'Chicoloapan',
  'Chiconcuac',
  'Chimalhuacan',
  'Donato Guerra',
  'Ecatepec de Morelos',
  'Ecatzingo',
  'Huehuetoca',
  'Hueypoxtla',
  'Huixquilucan',
  'Isidro Fabela',
  'Ixtapaluca',
  'Ixtapan de la Sal',
  'Ixtapan del Oro',
  'Ixtlahuaca',
  'Jaltenco',
  'Jilotepec',
  'Jilotzingo',
  'Jiquipilco',
  'Jocotitlan',
  'Joquicingo',
  'Juchitepec',
  'Lerma',
  'Luvianos',
  'Malinalco',
  'Melchor Ocampo',
  'Metepec',
  'Mexicaltzingo',
  'Morelos',
  'Naucalpan de Juarez',
  'Nezahualcoyotl',
  'Nextlalpan',
  'Nicolas Romero',
  'Nopaltepec',
  'Ocoyoacac',
  'Ocuilan',
  'El Oro',
  'Otumba',
  'Otzoloapan',
  'Otzolotepec',
  'Ozumba',
  'Papalotla',
  'La Paz',
  'Polotitlan',
  'Rayon',
  'San Antonio la Isla',
  'San Felipe del Progreso',
  'San Jose del Rincon',
  'San Martin de las Piramides',
  'San Mateo Atenco',
  'San Simon de Guerrero',
  'Santo Tomas',
  'Soyaniquilpan de Juarez',
  'Sultepec',
  'Tecamac',
  'Tejupilco',
  'Temamatla',
  'Temascalapa',
  'Temascalcingo',
  'Temascaltepec',
  'Temoaya',
  'Tenancingo',
  'Tenango del Aire',
  'Tenango del Valle',
  'Teoloyucan',
  'Teotihuacan',
  'Tepetlaoxtoc',
  'Tepetlixpa',
  'Tepotzotlan',
  'Tequixquiac',
  'Texcaltitlan',
  'Texcalyacac',
  'Texcoco',
  'Tezoyuca',
  'Tianguistenco',
  'Timilpan',
  'Tlalmanalco',
  'Tlalnepantla de Baz',
  'Tlatlaya',
  'Toluca',
  'Tonatico',
  'Tonanitla',
  'Tultepec',
  'Tultitlan',
  'Valle de Bravo',
  'Valle de Chalco Solidaridad',
  'Villa de Allende',
  'Villa del Carbon',
  'Villa Guerrero',
  'Villa Victoria',
  'Xalatlaco',
  'Xonacatlan',
  'Zacazonapan',
  'Zacualpan',
  'Zinacantepec',
  'Zumpahuacan',
  'Zumpango'
] as const;

export const CDMX_ALCALDIAS = [
  'Alvaro Obregon',
  'Azcapotzalco',
  'Benito Juarez',
  'Coyoacan',
  'Cuajimalpa de Morelos',
  'Cuauhtemoc',
  'Gustavo A. Madero',
  'Iztacalco',
  'Iztapalapa',
  'La Magdalena Contreras',
  'Miguel Hidalgo',
  'Milpa Alta',
  'Tlahuac',
  'Tlalpan',
  'Venustiano Carranza',
  'Xochimilco'
] as const;

export const CDMX_DESTINATION_HUBS = [
  'Alvaro Obregon - Observatorio (CETRAM)',
  'Alvaro Obregon - Tacubaya (Metro/CETRAM)',
  'Azcapotzalco - El Rosario (CETRAM)',
  'Azcapotzalco - Ferreria (Tren Suburbano)',
  'Benito Juarez - Centro Medico (Metro)',
  'Benito Juarez - Mixcoac (Metro)',
  'Coyoacan - Taxquena (CETRAM)',
  'Coyoacan - Universidad (Metro)',
  'Cuajimalpa - Santa Fe (Centro de Transferencia)',
  'Cuajimalpa - Centro Comercial Santa Fe (Nodo laboral)',
  'Cuauhtemoc - Buenavista (Suburbano/Metrobus)',
  'Cuauhtemoc - Hidalgo (Metro)',
  'Gustavo A. Madero - Indios Verdes (CETRAM)',
  'Gustavo A. Madero - Martin Carrera (Metro)',
  'Iztacalco - Ciudad Deportiva (Metro)',
  'Iztacalco - Puebla (Metro)',
  'Iztapalapa - Constitucion de 1917 (CETRAM)',
  'Iztapalapa - Santa Marta (CETRAM)',
  'La Magdalena Contreras - Hospital Angeles Pedregal',
  'La Magdalena Contreras - Periferico Sur / Luis Cabrera',
  'Miguel Hidalgo - Tacuba (Metro)',
  'Miguel Hidalgo - Auditorio (Metro)',
  'Milpa Alta - Milpa Alta Centro',
  'Milpa Alta - Villa Milpa Alta (Nodo local)',
  'Tlahuac - Tlahuac (Metro)',
  'Tlahuac - Olivos (Metro)',
  'Tlalpan - El Caminero (CETRAM)',
  'Tlalpan - Hospitales (Metro)',
  'Venustiano Carranza - Pantitlan (CETRAM)',
  'Venustiano Carranza - San Lazaro (Metro/TAPO)',
  'Xochimilco - Tasquena (CETRAM)',
  'Xochimilco - Tren Ligero Xochimilco',

  'Hospital General de Mexico Dr. Eduardo Liceaga',
  'Centro Medico Nacional Siglo XXI',
  'Hospital Juarez de Mexico',
  'Hospital General La Raza IMSS',
  'Hospital Infantil de Mexico Federico Gomez',
  'Hospital General Balbuena',
  'Hospital ABC Observatorio',
  'Instituto Nacional de Cancerologia (INCan)',

  'La Raza (Metro)',
  'Pino Suarez (Metro)',
  'Bellas Artes (Metro)',
  'Zapata (Metro)',
  'Chabacano (Metro)',
  'Guerrero (Metro)',
  'Politecnico (Metro)',
  'Chapultepec (Metro)',
  'Insurgentes (Metro)',
  'Tacuba (Metro)'
] as const;

export const TERMINALES_CDMX_TOP_15 = [
  'Indios Verdes',
  'Martin Carrera',
  'Pantitlan',
  'Observatorio',
  'Taxquena',
  'Tacubaya',
  'Chapultepec',
  'Buenavista',
  'La Raza',
  'Constitucion de 1917',
  'Pino Suarez',
  'Hidalgo',
  'San Lazaro',
  'Cuatro Caminos',
  'Politecnico'
] as const;

export const ROUTE_LOCATION_OPTIONS = [...EDOMEX_MUNICIPALITIES, ...CDMX_ALCALDIAS] as const;

export const ROUTE_SERVICE_SCOPE_OPTIONS = [
  { value: 'edomex_to_cdmx', label: 'EdoMex -> CDMX' },
  { value: 'cdmx_to_edomex', label: 'CDMX -> EdoMex' },
  { value: 'mixto_cdmx_edomex', label: 'Mixto CDMX / EdoMex' }
] as const;

export type RouteServiceScope = (typeof ROUTE_SERVICE_SCOPE_OPTIONS)[number]['value'];
