export const EDOMEX_MUNICIPALITIES = [
  'Acambay de Ruiz Castaneda',
  'Acolman',
  'Aculco',
  'Almoloya de Alquisiras',
  'Almoloya de Juarez',
  'Almoloya del Rio',
  'Amanalco',
  'Amatepec',
  'Amecameca',
  'Apaxco',
  'Atenco',
  'Atizapan',
  'Atizapan de Zaragoza',
  'Atlacomulco',
  'Atlautla',
  'Axapusco',
  'Ayapango',
  'Calimaya',
  'Capulhuac',
  'Coacalco de Berriozabal',
  'Coatepec Harinas',
  'Cocotitlan',
  'Coyotepec',
  'Cuautitlan',
  'Chalco',
  'Chapa de Mota',
  'Chapultepec',
  'Chiautla',
  'Chicoloapan',
  'Chiconcuac',
  'Chimalhuacan',
  'Donato Guerra',
  'Ecatepec de Morelos',
  'Ecatzingo',
  'Huehuetoca',
  'Hueypoxtla',
  'Huixquilucan',
  'Isidro Fabela',
  'Ixtapaluca',
  'Ixtapan de la Sal',
  'Ixtapan del Oro',
  'Ixtlahuaca',
  'Jaltenco',
  'Jilotepec',
  'Jilotzingo',
  'Jiquipilco',
  'Jocotitlan',
  'Joquicingo',
  'Juchitepec',
  'Lerma',
  'Malinalco',
  'Melchor Ocampo',
  'Metepec',
  'Mexicaltzingo',
  'Morelos',
  'Naucalpan de Juarez',
  'Nezahualcoyotl',
  'Nextlalpan',
  'Nicolas Romero',
  'Nopaltepec',
  'Ocoyoacac',
  'Ocuilan',
  'El Oro',
  'Otumba',
  'Otzoloapan',
  'Otzolotepec',
  'Ozumba',
  'Papalotla',
  'La Paz',
  'Polotitlan',
  'Rayon',
  'San Antonio la Isla',
  'San Felipe del Progreso',
  'San Martin de las Piramides',
  'San Mateo Atenco',
  'San Simon de Guerrero',
  'Santo Tomas',
  'Soyaniquilpan de Juarez',
  'Sultepec',
  'Tecamac',
  'Tejupilco',
  'Temamatla',
  'Temascalapa',
  'Temascalcingo',
  'Temascaltepec',
  'Temoaya',
  'Tenancingo',
  'Tenango del Aire',
  'Tenango del Valle',
  'Teoloyucan',
  'Teotihuacan',
  'Tepetlaoxtoc',
  'Tepetlixpa',
  'Tepotzotlan',
  'Tequixquiac',
  'Texcaltitlan',
  'Texcalyacac',
  'Texcoco',
  'Tezoyuca',
  'Tianguistenco',
  'Timilpan',
  'Tlalmanalco',
  'Tlalnepantla de Baz',
  'Tlatlaya',
  'Toluca',
  'Tonatico',
  'Tonanitla',
  'Tultepec',
  'Tultitlan',
  'Valle de Bravo',
  'Valle de Chalco Solidaridad',
  'Villa de Allende',
  'Villa del Carbon',
  'Villa Guerrero',
  'Villa Victoria',
  'Xonacatlan',
  'Zacazonapan',
  'Zacualpan',
  'Zinacantepec',
  'Zumpahuacan',
  'Zumpango',
  'Cuautitlan Izcalli',
  'Luvianos',
  'San Jose del Rincon',
  'Sultepec',
  'Tepetlixpa',
  'Xalatlaco'
] as const;


export const EDOMEX_ROUTE_PICKUP_POINTS = [
  'Tepexpan - Centro / Plaza principal',
  'Tepexpan - Carretera Mexico-Tepexpan / acceso principal',
  'Ojo de Agua - Centro / Plaza Ojo de Agua',
  'Ojo de Agua - Real del Sol / Boulevard Ojo de Agua',
  'San Cristobal Ecatepec - Centro / Catedral',
  'San Cristobal Ecatepec - Palacio Municipal',
  'Acolman - Centro / Palacio Municipal',
  'Tecamac - Centro / Palacio Municipal',
  'Tecamac - Los Heroes Tecamac',
  'Ecatepec - Las Americas / Plaza comercial',
  'Ecatepec - Ciudad Azteca / Metro Linea B',
  'Coacalco - Plaza Coacalco',
  'Tultitlan - Centro',
  'Cuautitlan Izcalli - Centro Urbano'
] as const;

export const CDMX_DESTINATION_HUBS = [
  'Gustavo A. Madero - Indios Verdes (CETRAM)',
  'Gustavo A. Madero - Martin Carrera (Metro)',
  'Gustavo A. Madero - La Raza (Metro/Hospital)',
  'Gustavo A. Madero - Politecnico (Metro)',
  'Venustiano Carranza - San Lazaro (Metro/TAPO)',
  'Venustiano Carranza - Pantitlan (CETRAM)',
  'Cuauhtemoc - Buenavista (Suburbano/Metrobus)',
  'Cuauhtemoc - Hidalgo (Metro)',
  'Miguel Hidalgo - Tacuba (Metro)',
  'Miguel Hidalgo - Chapultepec (Metro)',
  'Azcapotzalco - El Rosario (CETRAM)',
  'Benito Juarez - Centro Medico (Metro/Hospital)',
  'Tlalpan - Hospitales (Metro)',
  'Tlalpan - El Caminero (CETRAM)',
  'Coyoacan - Taxquena (CETRAM)',
  'Iztapalapa - Constitucion de 1917 (CETRAM)',
  'Iztapalapa - Santa Marta (CETRAM)',
  'Hospital General de Mexico Dr. Eduardo Liceaga',
  'Centro Medico Nacional Siglo XXI',
  'Hospital Juarez de Mexico',
  'Hospital General La Raza IMSS'
] as const;
export const CDMX_ALCALDIAS = [
  'Alvaro Obregon',
  'Azcapotzalco',
  'Benito Juarez',
  'Coyoacan',
  'Cuajimalpa de Morelos',
  'Cuauhtemoc',
  'Gustavo A. Madero',
  'Iztacalco',
  'Iztapalapa',
  'La Magdalena Contreras',
  'Miguel Hidalgo',
  'Milpa Alta',
  'Tlahuac',
  'Tlalpan',
  'Venustiano Carranza',
  'Xochimilco'
] as const;

export const ROUTE_LOCATION_OPTIONS: readonly string[] = Array.from(new Set([...EDOMEX_ROUTE_PICKUP_POINTS, ...EDOMEX_MUNICIPALITIES, ...CDMX_ALCALDIAS, ...CDMX_DESTINATION_HUBS]));

export const ROUTE_SERVICE_SCOPE_OPTIONS = [
  'edomex_to_cdmx',
  'cdmx_to_edomex',
  'mixto_cdmx_edomex'
] as const;

export type RouteServiceScope = (typeof ROUTE_SERVICE_SCOPE_OPTIONS)[number];

export const ROUTE_SERVICE_SCOPE_LABEL: Record<RouteServiceScope, string> = {
  edomex_to_cdmx: 'EdoMex -> CDMX',
  cdmx_to_edomex: 'CDMX -> EdoMex',
  mixto_cdmx_edomex: 'Mixto CDMX / EdoMex'
};

